language: node_js
node_js: stable

addons: # Travis CI建议加的，自动更新api
  apt:
    update: true

cache:
  directories: 
  - node_modules # 缓存 node_modules

install:
- npm install # 初次安装，在CI环境中，执行安装npm依赖

# before_script: 

script:
- hexo g # 执行 hexo generate，把文章编译到public中
- cd ./public
- ls

after_success: # 执行script成功后，进入到public，把里面的代码提交到博客的gh-pages分支
- git init
- git config user.name "Leslie-Luo"
- git config user.email "921110219@qq.com"
- git add .
- git commit -m "TravisCI 自动部署"
- git push --force --quiet "https://${GIT_TOKEN}@${GH_REF}" master:master

branches:
  only:
  - dev # CI 只针对分支 dev

env:
  global: # 全局变量，上面的提交到github的命令有用到
  - GH_REF: github.com/Leslie-Luo/blog.git
  - secure: 
# secure是自动生成的，执行`travis encrypt 'GH_TOKEN=${your_github_personal_access_token}' --add`
